"""create all table

Revision ID: f0f0f5597ffd
Revises: dc4a10a02a74
Create Date: 2022-09-16 18:14:48.435728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f0f5597ffd'
down_revision = 'dc4a10a02a74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('name', sa.String(), nullable=False))
    op.add_column('post', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('post', sa.Column('gender', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'gender')
    op.drop_column('post', 'age')
    op.drop_column('post', 'name')
    # ### end Alembic commands ###
