name: Build and Deploy code  #workflow name user defined

#it tells when the ci/cd pipeline should run or to trigger this code, if u want to run push use on:push, wanna run pull use on:pull-request
# wanna run both req then use under code 
on: [push,pull_request]

jobs:             #set of steps used to run
  job1: 
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTE: 60

    runs-on: ubuntu-latest   # specifying os 
    steps:
      - name: pulling git repo           
        uses: actions/checkout@v3           
      - name: Install python version 3.10
        uses: actions/setup-python@v4            
        with:
          python-version: "3.10"
      - name: update pip
        run: python -m pip install --upgrade pip               
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest


  