name: Build and Deploy code  #workflow name user defined

#it tells when the ci/cd pipeline should run or to trigger this code, if u want to run push use on:push, wanna run pull use on:pull-request
# wanna run both req then use under code 
on: [push,pull_request]

jobs:             #set of steps used to run
  job1: 
    runs-on: ubuntu-latest   # specifying os 
    steps:
      - name: pulling git repo           
        uses: actions/checkout@v3           
      # - name: say hai to mercy              #sample code
      #   run: echo "Hai Juju"
      - name: Install python version 3.10
        uses: actions/setup-python@v4            
        with:
          python-version: "3.10"
      - name: update pip
        run: python -m pip install --upgrade pip               
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest


  